### ISSUE TITLE
Persist the labels tag from OpenShift by expanding it via a dot notation

### ISSUE THREAD

**Issue by stefannegrea** [hawkular/hawkular-openshift-agent#141]
The `labels` tag should be persisted using an expanded dot notation. This will allow easier queries when the tag query language is updated to support the dot character. For more details about updating the tag query language visit [HWMETRICS-611](https://issues.jboss.org/browse/HWKMETRICS-611)

For example:
```
labels: {
 label1: value1,
 label2: value2
}
```

should be persisted as:
```
[labels.label1: value1, labels.label2: value2]
```

**Comment by jmazzitelli** [comment]
Just so we are clear what we are going to implement. Pod label docs are here:

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html#labels
https://kubernetes.io/docs/user-guide/labels/

An example is this yaml snippet of a pod config:

```
apiVersion: v1
kind: Pod
metadata:
  name: some-pod-9g33p
  namespace: myproject
  uid: 6d506b0a-fd30-11e6-ad52-54ee7549ae45
  labels:
    some-label1: some-value1
    some-label2: some-value2
```

The way the current PR is implemented to support this enhancement request (see PR #140) is that when this pod's metrics are stored, each metric definition within Hawkular-Metrics will have one tag per pod label, with the tag names prefixed with a particular prefix string ("labels." will be our default prefix to match what this issue's description says).

In the example above, there are two pod labels (some-label1 and some-label2) so for a metric stored for this pod, that metric's definition will have two tags, `labels.some-label1` with tag value of `some-value1` and tag name `labels.some-label2` with a tag value of `some-value2`.

This is what I assume this enhancement request is asking for.

This will introduce a new setting in the agent config:

```
kubernetes:
  pod_label_tags_prefix: labels.
```
