### ISSUE TITLE
[RFE] Support patterns on metrics definition for Jolokia endpoints

### ISSUE THREAD

**Issue by ljuaneda** [hawkular/hawkular-openshift-agent#152]
It would be great to let the agent discover the metrics on jolokia endpoints.
By now, we have to declare every single metric name you need.

For example to get all metrics about HeapMemory, you'll to declare :
```
      metrics:
      - name: java.lang:type=Memory#HeapMemoryUsage#max
        type: gauge
        description: Heap Memory Usage Max
        tags:
          resource_id: memory/heap memory usage
        units: B
      - name: java.lang:type=Memory#HeapMemoryUsage#committed
        type: gauge
        description: Heap Memory Usage Committed
        tags:
          resource_id: memory/heap memory usage
        units: B
      - name: java.lang:type=Memory#HeapMemoryUsage#init
        type: gauge
        description: Heap Memory Usage Init
        tags:
          resource_id: memory/heap memory usage
        units: B
      - name: java.lang:type=Memory#HeapMemoryUsage#used
        type: gauge
        description: Heap Memory Usage Used
        tags:
        resource_id: memory/heap memory usage
        units: B
```

I would like to set only one definition like :
```
- path: java.lang:type=Memory#HeapMemoryUsage
  name: java.lang:type=Memory#HeapMemoryUsage#$1
  description: Heap Memory Usage ($1)
  type: gauge
  tags:
    resource_id: memory/heap memory 
  units: B
```
HOSA could gather all that in one call and store the result to a distinguished metric name based on the jolokia response:
```
[root@siy05ez1:~]# curl -ks -H "Authorization: Bearer $(oc sa get-token management-admin -n management-infra)" -H "Content-Type: application/json" --cert /etc/origin/master/master.proxy-client.crt --key /etc/origin/master/master.proxy-client.key "https://10.130.5.35:8778/jolokia/read/java.lang:type=Memory/HeapMemoryUsage" | jq
{
  "timestamp": 1489759426,
  "status": 200,
  "request": {
    "mbean": "java.lang:type=Memory",
    "attribute": "HeapMemoryUsage",
    "type": "read"
  },
  "value": {
    "max": 487587840,
    "committed": 487587840,
    "init": 536870912,
    "used": 177185456
  }
}
```

Another and more tricky example :
Jolokia API supports wildcards (*) which match everything in the selected level.
```
[root@siy05ez1:~]# curl -ks -H "Authorization: Bearer $(oc sa get-token management-admin -n management-infra)" -H "Content-Type: application/json" --cert /etc/origin/master/master.proxy-client.crt --key /etc/origin/master/master.proxy-client.key "https://10.130.5.35:8778/jolokia/read/jboss.as:subsystem=datasources,data-source=*,statistics=pool/*" | jq
{
  "timestamp": 1489760745,
  "status": 200,
  "request": {
    "mbean": "jboss.as:data-source=*,statistics=pool,subsystem=datasources",
    "type": "read"
  },
  "value": {
    "jboss.as:data-source=BDD_RNXQG1,statistics=pool,subsystem=datasources": {
      "AverageBlockingTime": 0,
      "MaxWaitTime": 0,
      "ActiveCount": 0,
      "CreatedCount": 0,
      "MaxCreationTime": 0,
      "MaxWaitCount": 0,
      "TotalCreationTime": 0,
      "AvailableCount": 0,
      "MaxUsedCount": 0,
      "TimedOut": 0,
      "statisticsEnabled": false,
      "TotalBlockingTime": 0,
      "AverageCreationTime": 0,
      "InUseCount": 0,
      "DestroyedCount": 0
    },
    "jboss.as:data-source=BDD_RNXUV_,statistics=pool,subsystem=datasources": {
      "AverageBlockingTime": 0,
      "MaxWaitTime": 0,
      "ActiveCount": 0,
      "CreatedCount": 0,
      "MaxCreationTime": 0,
      "MaxWaitCount": 0,
      "TotalCreationTime": 0,
      "AvailableCount": 0,
      "MaxUsedCount": 0,
      "TimedOut": 0,
      "statisticsEnabled": false,
      "TotalBlockingTime": 0,
      "AverageCreationTime": 0,
      "InUseCount": 0,
      "DestroyedCount": 0
    },
    "jboss.as:data-source=ExampleDS,statistics=pool,subsystem=datasources": {
      "AverageBlockingTime": 0,
      "MaxWaitTime": 0,
      "ActiveCount": 0,
      "CreatedCount": 0,
      "MaxCreationTime": 0,
      "MaxWaitCount": 0,
      "TotalCreationTime": 0,
      "AvailableCount": 0,
      "MaxUsedCount": 0,
      "TimedOut": 0,
      "statisticsEnabled": false,
      "TotalBlockingTime": 0,
      "AverageCreationTime": 0,
      "InUseCount": 0,
      "DestroyedCount": 0
    },
    "jboss.as:data-source=BDD_RNX,statistics=pool,subsystem=datasources": {
      "AverageBlockingTime": 0,
      "MaxWaitTime": 0,
      "ActiveCount": 0,
      "CreatedCount": 0,
      "MaxCreationTime": 0,
      "MaxWaitCount": 0,
      "TotalCreationTime": 0,
      "AvailableCount": 0,
      "MaxUsedCount": 0,
      "TimedOut": 0,
      "statisticsEnabled": false,
      "TotalBlockingTime": 0,
      "AverageCreationTime": 0,
      "InUseCount": 0,
      "DestroyedCount": 0
    },
    "jboss.as:data-source=BDD_RNXK61,statistics=pool,subsystem=datasources": {
      "AverageBlockingTime": 0,
      "MaxWaitTime": 0,
      "ActiveCount": 0,
      "CreatedCount": 0,
      "MaxCreationTime": 0,
      "MaxWaitCount": 0,
      "TotalCreationTime": 0,
      "AvailableCount": 0,
      "MaxUsedCount": 0,
      "TimedOut": 0,
      "statisticsEnabled": false,
      "TotalBlockingTime": 0,
      "AverageCreationTime": 0,
      "InUseCount": 0,
      "DestroyedCount": 0
    }
  }
}
```

I would like to set only one definition like :
```
- pattern: jboss.as:subsystem=datasources,data-source=*,statistics=pool#*
  name: jboss.as:subsystem=datasources,data-source=$1,statistics=pool#$2
  description:  Datasource $1 $2
  tags:
    resource_id: datasource/statistics
```
type defaults to gauge when not specified.

And, what would be really nice to have, is the ability to exclude some results from the jolokia response.
Here for example, I don't care about the ExampleDS datasource....
