### ISSUE TITLE
be able to exclude metrics

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#154]
Agent can be told to collect Jolokia MBeans using MBean patterns (e.g. domain:type=*).
Agent can also be told to collect Prometheus metrics that are labeled (e.g. if a metric named "foo" is labeled, all labeled metrics are stored as different time series).

It would be nice to be able to tell the agent to exclude certain metrics. For example if a set of JMX MBeans are:

* domain:type:one
* domain:type:two
* domain:type:A
* domain:type:B

We should be able to tell the agent to exclude the "A" and "B" mbeans but still collect metrics from "one" and "two". So perhaps something like this can be in the config file (this is just a guess how it could be implemented, but you get the idea):

```
metrics:
- name: domain:type:*#*
  exclude:
  - type: A
  - type: B
```

We need to support being able to exclude based on multiple labels:

```
metrics:
- name: domain:type:*,subtype=*#*
  exclude:
  - type: A
    subtype: Aprime
  - type: B
    subtype: Bprime
```
