### ISSUE TITLE
Unable to get correct url endpoints which is running outside of OpenShift

### ISSUE THREAD

**Issue by hardbone12** [hawkular/hawkular-openshift-agent#175]
I Add this ```configMap``` to HOSA daemonSet YAML to inherit some ```cadvisor``` metrics which i need:
```
endpoints:
- type: "prometheus"
  url: "https://${CADVISOR_HOSTNAME}:10250/metrics"
  credentials:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
  identity:
    cert_file: /cadvisor/ca.crt
  collection_interval: 1m
```
But it seems hosa does not know the url in this configuration

```
I0831 08:21:36.349645     140 discovery.go:379] TRACE: Added configmap [hawkular-openshift-agent-configuration] for namespace [default]=ConfigMap[default:hawkular-openshift-agent-configuration]: endpoints:
- type: prometheus
  enabled: "true"
  protocol: ""
  port: 0
  path: ""
  tls: {}
  credentials:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
  collection_interval: 1m
  tags: {}
  metrics: []
```

**Comment by jmazzitelli** [comment]
Based on what you said, what I assume you are doing is running HOSA inside of OpenShift but wanting to collect data from some endpoint running outside of OpenShift.

The first thing I notice is that the snippet of YAML you provided seems incorrect. Endpoints don't have their own "Identity" - in other words, Identity identifies HOSA itself (and HOSA only has a single identity). Thus, the Identity is for the main agent configuration and not within Endpoints. See: https://github.com/hawkular/hawkular-openshift-agent/blob/master/config/config.go#L147-L155

In addition, that log message you provided is dumping a configmap's K8sEndpoint : https://github.com/hawkular/hawkular-openshift-agent/blob/master/k8s/configmap_entry.go#L40-L56

but your YAML you provide is following the Endpoint schema (with your "extra" Identity that is invalid): https://github.com/hawkular/hawkular-openshift-agent/blob/master/collector/metrics_endpoint.go#L54-L71

So, in other words, I'm all kinds of confused about your configuration and setup :)

Can you provide more details? Perhaps attach the full HOSA configuration file and the logs at HOSA startup.

If what I think you are trying to do is what you are really trying to do (run HOSA inside OS but collect metrics from outside OS) you need to provide endpoints within the HOSA configuration itself - in other words, inside this config.yaml: https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent-configmap.yaml#L10

NOT inside this hawkular-openshift-agent configmap: https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent-configmap.yaml#L46

(that latter one is to tell HOSA to collect metrics from itself which of course would be running in OS so it needs to eat its own dogfood and read a configmap like any other OpenShift-deployed pod)

See this example yaml to show how external endpoints can be defined (note, this example yaml is used when running HOSA outside of OS, but the idea is the same - that being "endpoints" is placed within the main config - so you would do the same in the HOSA main config.yaml):

https://github.com/hawkular/hawkular-openshift-agent/blob/master/config.yaml

**Comment by hardbone12** [comment]
You're right. The "Identity" configuration i made some mistake.
First, I'm thinking about whether endpoints support authentication, which means the endpoints have some security issue, maybe endpoints only allowed for internal using...(Just a idea)
Secound,  I'm trying to collect the cadvisor metrics data which is running in the openshift nodes to the hosa, because the official suggestion is using "heapster", which can only control the global collection interval.
So, cadvisor can output "prometheus" endpoint directly, that is 
```url: "https://${CADVISOR_HOSTNAME}:10250/metrics"```
It requires certificate and bearer token authentication.

Any advice is appreciated

**Comment by jmazzitelli** [comment]
>  whether endpoints support authentication, which means the endpoints have some security issue

Yes, HOSA supports authentication settings per endpoint. See the "[Credentials](https://github.com/hawkular/hawkular-openshift-agent/blob/master/config/security/config_security.go#L32-L39)" and "[TLS](https://github.com/hawkular/hawkular-openshift-agent/blob/master/config/security/config_security.go#L44-L46)" sections under the [Endpoints](https://github.com/hawkular/hawkular-openshift-agent/blob/master/collector/metrics_endpoint.go#L65-L66) config.

I've never tried to do what you are trying to do, but presumably you would have to assign a cert to your agent and configure it in the agent's Identity. Then you define the external "endpoint" in HOSA's main config pointing to the URL with the appropriate bearer token in the "Credentials" section of the endpoint definition. It's possible you need to enable the [Skip_Certificate_Validate setting in the endpoint's TLS config](https://github.com/hawkular/hawkular-openshift-agent/blob/master/config/security/config_security.go#L45).

Note that the debug logs for the agent should provide details on what is going wrong if your config is invalid. Start HOSA with the verbose level at 4 or higher - see https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent.yaml#L86 for an example. There is a trace level (-v 5) but I don't think that deep of logs will provide any more information needed and would just make the logs really noisy.

**Comment by hardbone12** [comment]
I'll try it, Thank you

**Comment by hardbone12** [comment]
```
config.yaml: |-
    kubernetes:
      tenant: ${POD:namespace_name}
    hawkular_server:
      url: https://hawkular-metrics.openshift-infra.svc.cluster.local
      credentials:
        username: secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.username
        password: secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.password
      ca_cert_file: secret:openshift-infra/hawkular-metrics-certs/tls.crt
    emitter:
      status_enabled: true
    collector:
      max_metrics_per_pod: 5000
      minimum_collection_interval: 10s
      default_collection_interval: 30s
      metric_id_prefix: pod/${POD:uid}/custom/
      pod_label_tags_prefix: labels.
      tags:
        metric_name: ${METRIC:name}
        description: ${METRIC:description}
        units: ${METRIC:units}
        namespace_id: ${POD:namespace_uid}
        namespace_name: ${POD:namespace_name}
        node_name: ${POD:node_name}
        pod_id: ${POD:uid}
        pod_ip: ${POD:ip}
        pod_name: ${POD:name}
        pod_namespace: ${POD:namespace_name}
        hostname: ${POD:hostname}
        host_ip: ${POD:host_ip}
        labels: ${POD:labels}
        cluster_name: ${POD:cluster_name}
        resource_version: ${POD:resource_version}
        type: pod
        collector: hawkular_openshift_agent
        custom_metric: true
    endpoints:
        - type: "prometheus"
          url: "https://node1.example.com:10250/metrics"
          credentials:
            token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
          tls:
            skip_certificate_validation: true
          collection_interval: 30s
          tags:
            endpoint-name: node1-cadvisor
        - type: "prometheus"
          url: "https://node2.example.com:10250/metrics"
          credentials:
            token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
          tls:
            skip_certificate_validation: true
          collection_interval: 30s
          tags:
            endpoint-name: node2-cadvisor
        - type: "prometheus"
          url: "https://node3.example.com:10250/metrics"
          credentials:
            token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
          tls:
            skip_certificate_validation: true
          collection_interval: 30s
          tags:
            endpoint-name: node3-cadvisor
```
I changed the configuration, it seems working now from log.
```
I0901 02:52:41.026154       1 prometheus_metrics_collector.go:97] DEBUG: Told to collect all Prometheus metrics from [https://node1.example.com:10250/metrics]
I0901 02:53:41.657816       1 metrics_storage.go:167] DEBUG: Stored datapoints for [2343] metrics
```
But, i hava another question, there are three endpoints in global configuration, and the hosa-agent daemonSet runs on three OS node, how does these three agents collecting three endpoints separately? Or collecting three copies of endpoints data each?
