### ISSUE TITLE
name of annotation - change to use standard?

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#27]
Today, a pod must have an annotation named "hawkular-openshift-agent" whose value is the name of a configmap. Inside the config map, there must be a data entry called the same thing "hawkular-openshift-agent". 

I see existing annotations have a common format - prefix (which mostly looks like domain names), followed by a slash, followed by some name - such as `openshift.io/scc` and `kubernetes.io/created-by` and `openshift.io/deployment.name`.

The reason I named it "hawkular-openshift-agent" without a prefix is because that is the same name as the configmap data entry - so it is easy to remember (they are just always the same so you don't have to ask, "What's the annotation name again? Is it "hawkular.io/configmap" or is it "hawkular-openshift-agent"? Configmap data entries are prohibited from special characters like "/" - when I try I get this error:

    data[hawkular.io/configmap]: Invalid value: "hawkular.io/configmap": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*

so looks like dot, dash, letters and numbers only.

Anyway, should we just say screw it and make them different just to conform to the "prefix/name" standard for annotation names? If so, what should we name both the annotation and the configmap entry name?

I'm thinking something along the lines of:

annotation name = `hawkular.org/configmap`
configmap data entry name = `hawkular-openshift-agent`

So keep the configmap data entry name the same as it is, but change the annotation name.

This change would affect two lines of code here: https://github.com/hawkular/hawkular-openshift-agent/blob/master/k8s/discovery.go#L17-L20

**Comment by jmazzitelli** [comment]
@mwringe what do you think? I'm thinking of making this change. The annotation can be "hawkular.org/configmap" (unless it should be something else?) and the configmap data entry name remains "hawkular-openshift-agent" so the configmap would look something like:

````
kind: ConfigMap
apiVersion: v1
metadata:
  name: this-name-must-match-the-value-of-the-annotation # <--- see here
  namespace: the-namespace
data:
  hawkular-openshift-agent: | # <--- see here
    endpoints:
    - ...and the rest of the Hawkular OpenShift Agent yaml config here...
````
