### ISSUE TITLE
Named tags and additional tags

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#56]
All metadata about a metric in Hawkular Metrics is stored as a tag. Right now when someone creates a metric definition, they are able to add to that metric additional tags they would like to add. But there may be special tags we want to apply to metrics in a more structured manner. 

For instance, having a 'unit' tag would be very useful to determine what unit the metric is being gathered in.

Currently a user could add a 'unit' tag to the list of tags, and this would work, but since its a part of a custom list its hard to enforce this naming. Some people may call it 'unit' while others may call it 'units', or they may have a mix themselves between the pods they are monitoring.

It may make sense to move something like this outside of the 'tags' list and to rename the 'tags' list to 'additional-tags' (which also makes it clear that this is not the only list of tags to be applied to the metric, but a list of extra ones to be added).

Anything outside of the 'additonal-tags' list would have to be properly named so there would be no issues with expected tags being under a slightly different tag name.

eg:

```
endpoints:
- type: jolokia
  metrics:
  - name: java.lang.type=Threading#ThreadCount
    type: gauge
    unit: threads
    additional-tags:
      my-metric-tag: the-metric-tag-value
      my-other-metric-tag: the-metric-tag-value
```
