### ISSUE TITLE
Jolokia Metric Name

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#57]
Right now we are setting the `name` of the jolokia metric to the mbean and its path where the metric can be found (https://github.com/hawkular/hawkular-openshift-agent/blob/master/hack/jolokia-wildfly-example/jolokia-wildfly-configmap.yaml#L14). I don't believe naming this `name` is accurate here.

We may want to rename this to make it more clear what it is.

Reserving `name` for a human readable value may also make sense, but we are also not doing this for prometheus endpoints either. We may want to come up with a consistent naming scheme between different endpoint types.

**Comment by jmazzitelli** [comment]
This is the "Name" field of the generic "MonitoredMetric" structure ( https://github.com/hawkular/hawkular-openshift-agent/blob/master/collector/metrics_endpoint.go#L36-L48 ) - which is used in the generic "Endpoint" structure ( https://github.com/hawkular/hawkular-openshift-agent/blob/master/collector/metrics_endpoint.go#L50-L64 ) - the Endpoint structure having shared usage across the different endpoint types (today there are two: Jolokia, and Prometheus, with presumably more types possible in the future). Sharing a single MonitoredMetric YAML structure in a single shared Endpoint structure makes the YAML consistent across the different endpoint types (the metric name is always stored in the name field - but the format/syntax of that metric name is dependent on the type of endpoint; e.g. its an MBean object name for jolokia endpoints, a metric name in the form "some_name" for Prometheus).

So the idea is this is the "metric name" as known to the endpoint.

The metric ID (that which is stored in H-Metrics to identify this metric's data) is by default this "name" unless you tell the agent what you want its ID to be - that is what the optional ID field is for: https://github.com/hawkular/hawkular-openshift-agent/blob/master/collector/metrics_endpoint.go#L44

So the problem to solve if we are to change "name" to something else (say "object-name" for jolokia endpoints and "metricName" for prometheus endpoints) is how to share this MonitoredMetric structure across all endpoint types but yet have the field names be different depending on the endpoint type. I don't know how to do this in Go. Unless we take out the generic nature of these YAML structures and just create different YAML structures per endpoint type - so instead of:

```
endpoints:
 - type: prometheus
   protocol: "http"
   metrics:
   - name: process_virtual_memory_bytes
   ...
 - type: jolokia
   protocol: "http"
   metrics:
   - name: java.system:type=Runtime
   ...
```

We would do something like:

```
endpoints:
 - type: prometheus
   protocol: "http"
   prometheus-metrics:
   - metric-name: process_virtual_memory_bytes
   ...
 - type: jolokia
   protocol: "http"
   jolokia-metrics:
   - object-name: java.system:type=Runtime
   ...
```

I don't know. That seems kind of odd to have "type: jolokia" but then have a hard-coded "jolokia-metrics" field name.

Maybe split endpoints to be:

```
prometheus-endpoints:
   - protocol: http
     metrics:
     - metric-name: process_virtual_memory_bytes
...
jolokia-endpoints:
   - protocol: http
     metrics:
     - object-name: java.system:type=Runtime
...
```

Either way this is a lot of work (and will make the code more complicated) for little value. 

Another alternative is to figure out a better name to use than "name" that would be applicable across all endpoint types so all we would have to do is change the "Name" field in MonitoredMetric to something else more appropriate. Perhaps "metric-name" is good enough and meaningful for both Prometheus and Jolokia. Or perhaps "metric-identifier" (but then that sort of confuses it with the "id" field).
