### ISSUE TITLE
Metric discovery via volume declarations

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#70]
Due to potential upcoming security changes with OpenShift, it may not be possible to access information on a node about something which is not present on the node itself.

Currently we use an annotation ("hawkular-openshift-agent") on the pod to indicate that we want application metrics to be gathered, and the value of this tag is the name of a configmap to use. 

The problem is that since the configmap is not actually used by the pod, or anything else the node (its only referenced by name) we may not be able to gather information in the future.

One way around this would be to force the pod itself to use the configmap. Since the pod would now be actually using the configmap, it would be bound to something on the node and now accessible. 

One way we could do this it to require that the configmap be loaded to a specific location (in this case `/var/run/configmaps/hawkular.io/agent` which is a similar structure to what kubernetes uses for its service account secrets `/var/run/secrets/kubernetes.io/serviceaccount`)
```
      spec:
        containers:
        - image: hawkular/openshift-agent-example-prometheus-python:${IMAGE_VERSION}
          name: prometheus-python-example
          volumeMounts:
          - name: hawkular-agent-configuration
            mountPath: "/var/run/configmaps/hawkular.io/agent"
        volumes:
        - name: hawkular-agent-configuration
          configMap:
            name: prometheus-python-example
```
We would then just have to check which config map is set to mount at that particular volume.

We could have used a specific configmap name (eg `hawkular.io/agent/config`) which may have been easier to parse, but storing it at a specific location may have additional benefits we could leverage in the future (including being able to directly access the files from the node itself)

**Comment by jmazzitelli** [comment]
I'm going to play around with this and see if I can figure out how to do this. I'll try the way @mwringe describes it above.

@mwringe what happens if someone tries to deploy that entity but the config map specified in "volumes" does not yet exist? Does it bomb?  Does it silently ignore it and pick it up later at runtime if/when that configmap is created?

**Comment by jmazzitelli** [comment]
I have this working in [my own branch here](https://github.com/hawkular/hawkular-openshift-agent/compare/master...jmazzitelli:issue-70-refactor-discovery)

Seems to be working fine. The problem is (and we already knew this) its not very nice in that you can't turn on and off metric collection by adding or removing the annotation (since we don't use annotations anymore). You can't remove volume definitions on the fly like you can annotations.

I think I should add an "enabled" flag somewhere in the config map data entry to let you tell the agent to turn on or off collection for a specific endpoint (or maybe a global flag for all the endpoints). Not sure what is easily attainable, but it is annoying that we are losing the ability to turn on/off collections on the fly. Another alternative would be to retain the annotation only have its value be a boolean -- "true' means "collect metrics if this pod is properly configured" and "false" means "do not collect metrics from this pod even if it is properly configured with a volume/config map". I think I would prefer an "enabled' flag in the config map to let one turn on and off collection of endpoints individually (or collectively).

**Comment by jmazzitelli** [comment]
OK, this is now in a PR #72 

@mwringe take a look if you got time. Note that for this to work you do NOT actually have to mount the config map anywhere (I did not have to use volumeMounts - I just defined one volume in "volumes" and it works):

```
  volumes:
        - name: hawkular-openshift-agent
          configMap:
            name: prometheus-python-example
```

Volume name must be "hawkular-openshift-agent" - the config map name can be anything that is valid (i.e. the config map itself does not have to be named anything specific).

Note that nothing changed with respect to how config maps are written - same as before. The only thing that changed is the annotation lookup went away and the volume lookup was put in its place.

In addition, there is now an "Enabled" flag in the endpoints YAML. So if you want to disable an endpoint(s), you go into their configmaps, edit the config map set "Enabled" to either "true" or "false". These are picked up at runtime - no need to redeploy pods or change pod configs:

```
   endpoints:
    - type: jolokia
      enabled: false
      protocol: "http"
      ...
```
