### ISSUE TITLE
hawkular-openshift-agent cannot collect jolokia metrics in https: missing identity

### ISSUE THREAD

**Issue by akram** [hawkular/hawkular-openshift-agent#71]
I am deploying h-o-a with a DaemonSet in OpenShift with the following configuration:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hawkular-openshift-agent
spec:
  selector:
    matchLabels:
      name: hawkular-openshift-agent
  template:
    metadata:
      labels:
        name: hawkular-openshift-agent
    spec:
      containers:
      - command:
        - /opt/hawkular/hawkular-openshift-agent
        - -config
        - /hawkular-openshift-agent-configuration/config.yaml
        - -v
        - "4"
        env:
#        - name: HAWKULAR_OPENSHIFT_AGENT_CERT_FILE
#          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: HAWKULAR_SERVER_URL
          value: https://hawkular-metrics
        - name: HAWKULAR_SERVER_CA_CERT_FILE
          value: /hawkular-metrics-certificate/hawkular-metrics-ca.certificate
        - name: HAWKULAR_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              key: hawkular-metrics.username
              name: hawkular-metrics-account
        - name: HAWKULAR_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: hawkular-metrics.password
              name: hawkular-metrics-account
        image: hawkular/hawkular-openshift-agent:latest
        imagePullPolicy: Always
        name: hawkular-openshift-agent
        resources: {}
        securityContext:
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
            - SYS_CHROOT
          privileged: false
          runAsUser: 1000050000
          seLinuxOptions:
            level: s0:c7,c4
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /hawkular-metrics-certificate
          name: hawkular-metrics-certificate
        - mountPath: /hawkular-openshift-agent-configuration
          name: hawkular-openshift-agent-configuration
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: hawkular-agent-token-bkivw
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        hawkular-openshift-agent: "true"
      imagePullSecrets:
      - name: hawkular-agent-dockercfg-fckcj
      restartPolicy: Always
      securityContext:
        fsGroup: 1000050000
        seLinuxOptions:
          level: s0:c7,c4
      serviceAccount: hawkular-agent
      serviceAccountName: hawkular-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hawkular-metrics-certificate
        secret:
          secretName: hawkular-metrics-certificate
      - configMap:
          name: hawkular-openshift-agent-configuration
        name: hawkular-openshift-agent-configuration
      - name: hawkular-agent-token-bkivw
        secret:
          secretName: hawkular-agent-token-bkivw
```

The agent configmap is
```
kind: ConfigMap
apiVersion: v1
name: Hawkular OpenShift Agent Configuration
metadata:
  name: hawkular-openshift-agent-configuration
  labels:
    metrics-infra: agent
data:
  config.yaml: |
    collector:
      minimum_collection_interval_secs: 10
      metric_id_prefix: pod/${POD:uid}/custom/
      tags:
        metric_name: ${METRIC:name}
        description: ${METRIC:description}
        units: ${METRIC:units}
        namespace_id: ${POD:namespace_uid}
        namespace_name: ${POD:namespace_name}
        node_name: ${POD:node_name}
        pod_id: ${POD:uid}
        pod_ip: ${POD:ip}
        pod_name: ${POD:name}
        pod_namespace: ${POD:namespace_name}
        hostname: ${POD:hostname}
        host_ip: ${POD:host_ip}
        labels: ${POD:labels}
        type: pod
        collector: hawkular_openshift_agent
        custom_metric: true
```
And the application config map
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-metrics-config
data:
  hawkular-openshift-agent: |
    collection_interval_secs: 5
    endpoints:
    - type: prometheus
      protocol: http
      port: 9101
      path: /metrics
    - type: jolokia
      protocol: https
      port: 8778
      path: /jolokia
    identity:
```

If I try to deploy with an empty idendity defined, I see the following error log
```
W1221 14:33:19.343443       1 metrics_collector_manager.go:106] Failed to collect metrics from [https://10.1.6.5:8778/jolokia]. err=Failed to collect metrics from Jolokia endpoint [https://10.1.6.5:8778/jolokia]. err=Post https://10.1.6.5:8778/jolokia: EOF
```

If I add OpenShift master CA as a CA file, I get another error  because my private key is incorrect:

**Comment by jmazzitelli** [comment]
Don't you need SOME kind of cert for when connecting to https?

**Comment by jmazzitelli** [comment]
for the record, here is where the http client is built and you can see where the identity object is used to build the tls configuration: https://github.com/hawkular/hawkular-openshift-agent/blob/master/http/http_client.go#L36

**Comment by jmazzitelli** [comment]
@akram I'm wondering if your jolokia URL is correct. What do you see if you point a browser to https://10.1.6.5:8778/jolokia/version (or whatever accessible IP is available for that endpoint if any). Note the "/version" at the end). Just want to make sure that EOF isn't due to a bad URL.

**Comment by akram** [comment]
This also was my understanding but I was mistaken by another answer.
I realised now that jolokia is started this way in my container to monitor:
```
 /usr/lib/jvm/java-1.8.0/bin/java -javaagent:/opt/amq/jolokia.jar=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false 
```
Seems to be better now: I added two secrets containing my master.proxy-client.key and master.proxy-client.crt files and I am point to them with my HAWKULAR_OPENSHIFT_AGENT_CERT_FILE and HAWKULAR_OPENSHIFT_AGENT_PRIVATE_KEY_FILE.

Now I do have a 404 error: 
```
 metrics_collector_manager.go:106] Failed to collect metrics from [https://10.1.6.5:8778/jolokia]. err=Failed to collect metrics from Jolokia endpoint [https://10.1.6.5:8778/jolokia]. err=Jolokia request failed. 404/404 Not Found
```

**Comment by jmazzitelli** [comment]
First, make sure "/jolokia" the correct path to reach the Jolokia endpoint.

Second, I don't see you defining any metrics to actually collect. They look like this as an example:

https://github.com/hawkular/hawkular-openshift-agent/blob/master/hack/jolokia-wildfly-example/jolokia-wildfly-configmap.yaml#L13-L22

**Comment by akram** [comment]
yep, sorry, here is my correct configmap for my app:
I just set /jolokia/version as path, because /jolokia was giving 404
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-amq-4
data:
  hawkular-openshift-agent: |-
    collector:
      tags:
      - hawkular-openshift-agent: true
    collection_interval_secs: 5
    endpoints:
    - type: jolokia
      protocol: https
      port: 8778
      path: /jolokia/version
      metrics:
      - name: java.lang:type=Threading#ThreadCount
        type: counter
        id:   VM Thread Count
      - name: java.lang:type=Memory#HeapMemoryUsage#used
        type: gauge
        id:   VM Heap Memory Used

```
